[package]
name = "mustang"
version = "0.0.0"
authors = [
    "Dan Gohman <dev@sunfishcode.online>",
]
description = "Program startup written in Rust"
documentation = "https://docs.rs/mustang"
license = "Apache-2.0 WITH LLVM-exception OR Apache-2.0 OR MIT"
repository = "https://github.com/sunfishcode/mustang"
edition = "2018"
exclude = ["/.github"]
